import Head from "next/head";
import Container from "../styles/index";
import { useEffect, useState } from "react";
import Footer from "../components/Footer";
import List from "../components/List";

export default function Home() {
	const [loaded, setLoaded] = useState(false);

	const [lists, setLists] = useState();

	setTimeout(() => {
		setLoaded(true);
	}, 1500);

	useEffect(() => {
		fetch(`https://magickhub.vercel.app/api/data`)
			.then((response) => response.json())
			.then((data) => setLists(Object.values(data).map((item) => item)))
			.catch((err) => console.log(err));
	}, []);

	return (
		<>
			<Head>
				<title>Magick Hub | Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<Container>
				{!loaded && (
					<div className="loading">
						<img src="/assets/loading.jpg" alt="Loading..." />
					</div>
				)}
				<section>
					{lists &&
						lists.map((item, index) => <List listName={item} key={index} />)}
				</section>
				<Footer />
			</Container>
		</>
	);
}
