import { NextApiRequest, NextApiResponse } from "next";

const data = [
	{
		title: "Mitologia na visão de Jung",
		overview: [
			'Os arquétipos de Carl Jung são um conjunto de imagens, ideias e padrões de comportamento universais que existem no inconsciente coletivo da humanidade. Jung acreditava que esses arquétipos são uma espécie de "programa" inato que orienta a maneira como as pessoas percebem o mundo e se comportam.',
			"Existem muitos arquétipos diferentes, cada um com seu próprio conjunto de características e simbolismo. Alguns exemplos comuns incluem o herói, o sábio, o mago, a mãe, o pai e o trickster. Cada arquétipo representa uma força primordial que influencia a maneira como as pessoas pensam e agem.",
			"Jung também acreditava que os arquétipos estão presentes em muitas das histórias e mitos que as pessoas contam ao longo dos séculos. Por exemplo, muitas histórias de heróis seguem um padrão semelhante, em que o herói deve enfrentar uma série de desafios e provar sua coragem antes de finalmente alcançar a vitória.",
			"Os arquétipos são importantes porque ajudam as pessoas a entender a si mesmas e aos outros. Ao reconhecer os padrões de comportamento que estão em jogo, as pessoas podem começar a entender melhor por que agem de certas maneiras e como podem mudar para melhorar suas vidas.",
			"Nesse contexto, existem também implicações importantes para a psicologia e a terapia. Jung acreditava que o objetivo final da psicoterapia era ajudar as pessoas a se tornarem mais conscientes dos arquétipos em jogo em suas vidas e a encontrar maneiras de trabalhar com eles de maneira mais positiva e produtiva.",
		],
		address: "jung",
	},
	{
		name: "O herói",
		image_path: "/assets/archetypes/heroi.jpg",
		overview: [
			"O herói é um dos arquétipos de Jung mais conhecidos. Ele representa os indivíduos corajosos e bondosos, que lutam pelos seus ideais e que ajudam a quem estiver ao seu redor, sendo símbolos da justiça e da determinação. O seu objetivo é provar o seu valor por meio da coragem, fazendo o bem ao mundo. O seu grande medo é passar pela vida como alguém “acomodado” ou covarde.",
			"1. CORAGEM E DETERMINAÇÃO",
			"Talvez os traços mais facilmente reconhecíveis nos heróis sejam justamente a coragem e a determinação. Ser corajoso significa identificar riscos e reconhecer medos, mas agir mesmo assim, em busca dos seus objetivos. Já ser determinado significa lutar para alcançar as suas metas, mesmo que haja muitos obstáculos no caminho.",
			"Assim, os heróis sentem medo, mas agem sempre no sentido de superá-lo. Eles preferem sofrer algum tipo de derrota a lidar com a covardia de não ter tentado. Além disso, são persistentes e só descansam quando chegam ao estado desejado.",
			"2. TRABALHO DURO",
			"A vida dos heróis não é fácil. Quem os vê fazendo sucesso e colhendo os frutos pode não reconhecer os sacrifícios que foram necessários para chegar a esse momento. É o caso das trajetórias de muitos esportistas, líderes políticos honestos e empresários que alcançaram o sucesso, mas que enfrentaram muitas dificuldades no percurso.",
			"Por isso, os heróis encontram na realização dos seus sonhos a motivação para estudar, trabalhar, lutar pelas suas ideias e, com alguma frequência, enfrentar a oposição. O trabalho é duro, mas só serve para tornar ainda mais digno e nobre o fazer do herói.",
			"3. RESILIÊNCIA",
			"A resiliência é a propriedade física que alguns materiais têm de retornar ao seu estado original depois de terem sido submetidos a uma deformação elástica, como ocorre quando apertamos uma esponja de lavar louças.",
			"Metaforicamente, podemos dizer que o herói é um arquétipo resiliente, no sentido de que, mesmo enfrentando tantas dificuldades no seu caminho, ele não perde a coragem, a confiança em si mesmo e a vontade de vencer. Um atleta olímpico, por exemplo, pode ter que enfrentar dificuldades financeiras, ausência de patrocínio, falta de infraestrutura e concorrentes muito mais bem-preparados até conquistar um lugar ao sol, mas nem por isso deixa de se recuperar das dificuldades enfrentadas.",
			"4. VONTADE DE FAZER A DIFERENÇA NO MUNDO",
			"Os heróis não pensam em utilizar a sua coragem apenas em benefício próprio. Muitas vezes, o que eles mais desejam é levar mais qualidade de vida às pessoas que estiverem ao seu redor. Um exemplo da vida real é Chico Mendes, que lutou pela preservação do meio ambiente e por condições de trabalho e de vida mais dignas aos seringueiros da Amazônia.",
			"Muitas vezes, os ideais de um herói são tão fortes que ultrapassam até mesmo a própria vida, perpetuando-se entre as gerações futuras. Isso concretiza o desejo do herói de deixar a sua marca, ou seja, o seu legado no mundo.",
			"5. AMBIÇÃO POSITIVA E HONESTIDADE",
			"Todo herói é movido por ambições positivas, ou seja, por objetivos a serem alcançados. Nesse caso, podemos falar de metas que o beneficiam individualmente, mas também que podem servir aos seus amigos, familiares, colegas, vizinhos, ou a cidades e países inteiros.",
			"É importante ressaltar, porém, que a luta de todo herói é fundamentalmente conduzida pela honestidade e por um conjunto de valores sólidos. Ética, empatia, respeito e honestidade sempre guiam as suas ações.",
			"6. AUTOCONFIANÇA E VONTADE DE BRILHAR",
			"Matéria-prima da coragem, a autoconfiança é um traço típico dos heróis. Por mais que se questionem de tempos em tempos, em geral, eles confiam muito nos seus valores, na sua inteligência, nos seus conhecimentos e nas suas habilidades. Por isso, procuram colocar tudo isso em prática.",
			"A vontade de vencer na vida e de ajudar o outro também pode carregar consigo outro aspecto comum aos heróis: a vontade de brilhar. Eles gostam de ser admirados pelas pessoas ao redor, o que revela um pouco da vaidade que esse arquétipo contém.",
			"7. PONTOS VULNERÁVEIS: ARROGÂNCIA E DESCUIDO CONSIGO MESMO",
			"Dois aspectos do arquétipo do herói merecem atenção: por mais que ele seja um dos arquétipos mais admirados, o indivíduo que se identifica com ele deve tomar cuidado para que a autoconfiança não se torne arrogância. Nesse caso, ao invés de atrair a admiração das pessoas, o herói pode afastá-las.",
			"Além do mais, o herói também precisa ficar atento para não querer carregar o mundo nas costas. Na ficção, isso até pode ocorrer, mas na vida real, todo ser humano tem os seus limites físicos e mentais. Por isso, o excesso de esforços e de trabalho pode levar o herói ao adoecimento do corpo e/ou da mente.",
			"O herói é um dos arquétipos mais fáceis de reconhecer: é aquele indivíduo corajoso, que enfrenta os seus próprios medos e que luta pelos seus ideais sem desistir, muitas vezes lutando também por outras pessoas, e não apenas por si mesmo. Admirado, o herói tem valores sólidos e uma ambição honesta, mas não pode deixar de cuidar de si mesmo ou permitir que a arrogância coloque tudo a perder.",
		],
	},
	{
		name: "O Comum",
		image_path: "/assets/archetypes/homem-comum.jpg",
		overview: [
			"O “comum” é o arquétipo que representa as pessoas cujo perfil seja voltado às atividades cotidianas e à sua vontade de pertencer a um grupo social. O seu desejo é o de conectar-se com outras pessoas. Você, com certeza, conhece pessoas assim e até mesmo pode se identificar com esse arquétipo.",
			"1. NECESSIDADE DE PERTENCIMENTO",
			"A principal característica da pessoa comum é a necessidade de pertencimento. Ela não tem o objetivo de se destacar, de liderar ou de alcançar algo grandioso. Para ela, ser feliz é ter uma rotina e uma vida simples, em que consiga ser aceita e fazer parte de determinados grupos.",
			"Assim, essa pessoa valoriza muito a família, os amigos, o emprego e o relacionamento amoroso. Sente que esses são os verdadeiros pilares da sua trajetória, na busca pela felicidade.",
			"2. PERFIL AMIGÁVEL",
			"É justamente pensando em ser aceito que o arquétipo do comum procura desenvolver um perfil amigável. Assim, as suas atitudes do dia a dia revelam simpatia, empatia, altruísmo, solidariedade e bom humor.",
			"Essas pessoas também costumam ser muito prestativas, ou seja, se esforçam para ajudar ao próximo e criar com ele conexões positivas. Assim, gostam de conhecer as pessoas, mas precisam se esforçar para que essas conexões sejam mais profundas, e menos superficiais. É reconhecidamente um indivíduo bastante trabalhador e que consegue ser muito cooperativo e funcional, sobretudo nos trabalhos em equipe.",
			"3. HUMILDADE",
			"O comum é provavelmente o mais humilde dos arquétipos. Ele não tem grandes pretensões, como destacar-se por uma habilidade rara, assumir posições de liderança ou ser independente. Para ele, está tudo bem fazer parte de uma equipe e alcançar resultados coletivamente.",
			"Ele está em busca de aceitação e pertencimento, mais do que qualquer destaque ou reconhecimento individual. Isso não quer dizer, porém, que essa pessoa não tenha as suas ambições e objetivos na vida — a questão é que ela é apenas mais modesta e realista.",
			"4. REALISMO",
			"Por falar em ser realista, o realismo é justamente uma característica-chave de quem apresenta o perfil junguiano do “comum”. Assim, essas pessoas são o que é chamado popularmente de “pé no chão”, ou seja, aquelas pessoas que analisam as situações antes de tomar qualquer decisão e que são cautelosas ao definir metas para as diferentes áreas das suas vidas.",
			"Nos filmes, é comum enxergarmos um protagonista com ideias de grandeza, enquanto há um coadjuvante que o ajuda a enxergar as situações com mais realismo e sensatez. Esse coadjuvante provavelmente se enquadra no perfil do arquétipo “comum”.",
			"5. EMPATIA E DESEJO DE CONEXÃO",
			"Para conectar-se com outras pessoas, o comum é um dos arquétipos mais empáticos. Isso significa que ele é capaz de colocar-se mentalmente no lugar de outras pessoas, imaginando o que ele mesmo sentiria ou como agiria se estivesse naquela situação. Isso o ajuda a ser mais prestativo e altruísta.",
			"Consequentemente, essa pessoa comum consegue ser um amigo fiel e verdadeiro, capaz de ouvir e aconselhar o outro sem julgar e sem colocar-se em uma posição de superioridade. O que ele realmente deseja é criar conexões com as pessoas e fazer parte de grupos, pois, assim, se sente mais confiante e protegido.",
			"6. RISCO DE “PERDER A SI MESMO” PARA FAZER PARTE",
			"Um dos pontos de atenção para o arquétipo comum é que, com tanta necessidade de fazer parte de um grupo, ele pode acabar “perdendo a si mesmo”. Em geral, os indivíduos que se identificam com esse arquétipo não querem destaque individual e, por isso, gostam de fazer parte de grupos.",
			"Contudo, para pertencer a essas equipes, esse indivíduo pode perder a sua autenticidade, isto é, deixar de ser ele mesmo apenas para “caber nos moldes de aceitação” definidos pelo grupo em questão. Isso pode torná-lo menos feliz.",
			"7. MEDO DE OBTER ALGUM DESTAQUE",
			"Os maiores medos do arquétipo do comum são ficar de fora de algum grupo ou obter algum destaque. Tudo o que ele quer é fazer parte da sociedade, fazendo as suas coisas comuns e passar praticamente despercebido.",
			"Se, por acaso, ele começar a obter algum tipo de destaque — mesmo que positivo, como um desempenho excepcional no trabalho — ele pode se sentir desconfortável nessa posição. Na visão desse indivíduo, há mais segurança e satisfação se ele estiver apenas compondo um grupo do que trilhando um caminho individual, o que significaria mais pressão sobre si mesmo.",
			"O “comum” é um arquétipo junguiano bastante fácil de encontrar. Resumidamente, ele contempla todas as pessoas que gostam de se sentir pertencentes e de criar conexões, evitando destaques individuais. Ele pode ser feliz assim, mas deve tomar cuidado para não sabotar a si mesmo nessa desesperada ideia de “se encaixar” em algum lugar.",
		],
	},
	{
		name: "O Criador",
		image_path: "/assets/archetypes/criador.jpg",
		overview: [
			"O criador é um dos 12 arquétipos identificados por Jung. Ele representa todos os indivíduos que têm a criatividade como a sua característica principal, isto é, que gostam de criar coisas de valor duradouro. São pessoas que desenvolvem uma visão diferenciada para resolver problemas e que gostam de inovar.",
			"1. INOVAÇÃO",
			"Inovar significa fazer algo diferente, ou seja, algo que você nunca experimentou o que ninguém nunca fez. Os criadores têm essa característica, justamente porque valorizam a originalidade como uma virtude importante.",
			"Essas pessoas são reconhecidas por lançar sobre coisas comuns um olhar diferente, enxergando elementos que, muitas vezes, passam despercebidos pela maioria das pessoas. Assim, conseguem enxergar oportunidades de inovar onde ninguém mais vê. Isso permite que tenham aquelas ideias que provocam na sociedade aquela clássica reação: “como ninguém tinha pensado nisso antes?”.",
			"2. INSPIRAÇÃO",
			"A criatividade depende em parte da inspiração. Por isso, os criadores estão sempre se expondo a tudo aquilo que o mundo oferece que possa ser verdadeiramente inspirador. Esses indivíduos são, portanto, mais sensíveis à música, à arte e até mesmo às belezas naturais. Tudo isso os inspira a ter ideias criativas.",
			"Além de buscarem inspiração, os criadores também são inspiradores por natureza. Eles estimulam aqueles que estiverem ao seu redor a também serem mais originais e inovadores, desenvolvendo soluções diferenciadas e mais eficazes aos problemas do dia a dia.",
			"3. EXPERIMENTAÇÃO",
			"Fazer o que ninguém faz exige correr alguns riscos. Por isso, o criador é, em geral, um arquétipo que sabe a hora de ser corajoso e de experimentar coisas novas. Para essas pessoas, a rotina não é agradável. Tudo aquilo que é repetido perde a graça.",
			"Dessa forma, quem se identifica com esse arquétipo gosta de experimentar tudo aquilo que é novo. Uma nova rede social, um novo esporte, um novo restaurante, um novo estilo musical, um novo destino para conhecer, uma nova cultura, um novo passeio, um novo tipo de filme, enfim, tudo o que é novo é atraente. São pessoas sem preconceito e com a mente aberta, que desejam conhecer o que o mundo pode oferecer.",
			"4. REPERTÓRIO RICO E DIVERSIFICADO",
			"Algumas pessoas acreditam que a criatividade é um dom sobrenatural, que alguns indivíduos têm e que só aparece diante de um momento milagroso de inspiração. Na verdade, qualquer pessoa pode ser criativa, desde que enriqueça o seu repertório mental.",
			"O repertório mental do criador é extremamente rico. Esse tipo de pessoa assiste a diferentes filmes, lê vários livros, conversa com várias pessoas, ouve músicas de ritmos variados, conhece locais diversificados, enfim, explora o que aparecer para enriquecer o seu repertório. Quanto mais referências a pessoa tiver na sua mente, mais conseguirá ter ideias criativas quando quiser ou precisar.",
			"5. APEGO ÀS ARTES E À CULTURA",
			"É justamente pode gostar tanto da experimentação e do enriquecimento do repertório mental que o criador é um arquétipo quase sempre associado às artes e à cultura. Dessa forma, esses indivíduos tendem a ser apreciadores e também potenciais produtores da música, da literatura, da dança, do desenho, da escultura, do cinema, da arquitetura, entre outras expressões essencialmente criativas.",
			"O criador é, portanto, o arquétipo que mais investe, incentiva e constrói a cultura de uma localidade, sendo também aquele que mais consome essa cultura. Assim, é natural que essas pessoas ocupem profissões, como: arquitetos, músicos, publicitários, escritores, dramaturgos, desenhistas, e por aí vai.",
			"6. IMAGINAÇÃO PARA CRIAR E FAZER DIFERENTE",
			"Alguém, um dia, percebeu que era possível construir um vaso bonito e funcional a partir de uma garrafa pet. Esse é um exemplo simples de que o criador não precisa criar uma obra de arte a ser exposta no museu do Louvre para ser considerado criativo. É possível ser inovador mesmo em aspectos comuns do dia a dia.",
			"Por isso, tudo o que esse arquétipo desenvolve é a imaginação para fazer diferente. Enquanto 99% das pessoas descartariam a garrafa de alguma maneira, aquele 1% criador certamente pensaria em um novo uso àquele material.",
			"7. POSSÍVEL TENDÊNCIA AO TÉDIO E AO PERFECCIONISMO",
			"Para não dizer que tudo é um mar de rosas na vida do criador, é claro que também existem alguns pontos de atenção ao indivíduo com esse perfil — como, aliás, ocorre com todos os arquétipos.",
			"No caso do criador, ele deve tomar cuidado para não cair no perfeccionismo. Ele pode ficar tão obcecado em dar o melhor de si na sua criação que pode nunca ficar satisfeito com ela — como corre com alguns pintores, músicos e escritores.",
			"Além disso, outro ponto de atenção ao criador é o tédio. A vida não é feita só de momentos inovadores e estimulantes. Em alguns momentos, precisamos mesmo fazer aquilo que todos fazem: ir ao supermercado, pagar as contas, fazer faxina, e por aí vai. É bacana ser criativo, mas não é sempre que conseguimos.",
			"Concluindo, o criador é um arquétipo inovador na sua essência. Ele busca o que é novo, experimenta formas diferentes de agir e sempre alimenta o seu repertório mental. Assim, ele consegue enxergar o que ninguém mais vê e ter ideias que nem passaram pela cabeça de outras pessoas. Só é preciso ter cuidado com as armadilhas do tédio e/ou do perfeccionismo.",
		],
	},
	{
		name: "O Sábio",
		image_path: "/assets/archetypes/sabio.jpg",
		overview: [
			"Albert Einstein, Mark Zuckerberg e até mesmo o Mestre Yoda (do universo de Star Wars) são exemplos clássicos de pessoas ou personagens que traduzem a essência do arquétipo do sábio. O objetivo de quem tem esse arquétipo forte dentro de si é encontrar a verdade e utilizar a inteligência para compreender o mundo. São curiosos, inteligentes e ativos na compreensão dos fatos. Gostam de refletir e de estudar. Contudo, a sua fraqueza pode ser justamente um apego à teoria, deixando de colocar os seus saberes em prática.",
			"1. BUSCA PELA VERDADE",
			"O arquétipo do sábio reúne todas aquelas pessoas que estão continuamente em busca da verdade. Elas reúnem dados e informações, analisam e desenvolvem a inteligência para acumular e associar saberes, permitindo que cheguem a determinadas conclusões sobre fatos, pessoas, fenômenos, enfim, sobre a vida de maneira geral.",
			"Por isso, esses indivíduos não têm preguiça de ler, estudar, entrevistar pessoas, enfim, acumular material para refletir e chegar a determinadas conclusões. Tudo isso é feito sempre com método e lógica, priorizando o que é racional, em detrimento do que é emocional ou intuitivo.",
			"2. LADO HUMANISTA",
			"Um aspecto que precisa ser evidenciado sobre os sábios é que eles não são egoístas. Isso quer dizer que tudo aquilo que eles apuram sobre a verdade e sobre o conhecimento não é utilizado apenas em benefício próprio. Pelo contrário: essas pessoas querem divulgar aquilo que sabem justamente para oferecer à humanidade como um todo uma qualidade de vida maior.",
			"Por isso, o sábio também pode ser identificado pelo seu lado humanista, isto é, pela sua grande vontade de ajudar as pessoas, sejam elas quem forem. O seu conhecimento não é só para si, mas para ajudar a quem precisar.",
			"3. PERFIL ANALÍTICO",
			"O que torna uma pessoa sábia, porém, não é o simples fato de acumular informações. O que realmente faz a diferença é a capacidade dessas pessoas de associar informações e de extrair delas interpretações conclusivas sobre os fatos. Isso, naturalmente, depende de muita análise e reflexão.",
			"Diante disso, o sábio consegue ler diferentes conteúdos e obter, a partir deles, conhecimentos que outras pessoas teriam deixado passar. Esses indivíduos exercitam continuamente o hábito do estudo e também da associação de ideias, em busca da verdade. É o perfil mais representativo para professores, filósofos, especialistas, cientistas e detetives.",
			"4. AUTOCONHECIMENTO",
			"Uma característica muito interessante sobre o arquétipo do sábio é que ele não analisa apenas o mundo ao seu redor, mas também a si mesmo. Esse arquétipo representa as pessoas que refletem também sobre quem são, de onde vieram, para onde vão, por que estão aqui, enfim, aqueles questionamentos existenciais clássicos.",
			"O sábio percebe que quanto mais ele conhece a si mesmo, mais ele consegue obter resultados positivos nas diferentes áreas da sua vida. Por isso, ele mergulha no universo do “eu”, identificando os seus pontos fortes, bem como aqueles que precisam de correções e ajustes.",
			"5. APREÇO PELO ESTUDO",
			"O sábio valoriza o estudo. Dessa forma, as pessoas que se identificam com esse arquétipo são aquelas que gostam de ler, de viajar, de conversar com diferentes pessoas, de participar de palestras e exposições, de realizar cursos, enfim, de aumentar continuamente o seu repertório mental.",
			"Isso desenvolve nesses indivíduos a capacidade de obter dados, transformá-los em informações e conhecimento (contextualizando e associando esses saberes) e de transformar tudo isso em sabedoria (tentando colocar os seus aprendizados em prática). Dessa forma, são pessoas com a mente aberta, sem preconceitos, que sabem que podem aprender algo positivo em diferentes lugares.",
			"6. DESCONFIANÇA E INVESTIGAÇÃO",
			"O sábio é desconfiado. Essa característica, ao contrário do que possa parecer, é muito positiva. Esse indivíduo é aquele que questiona aquilo em que todo mundo acredita e que todo mundo toma como verdade. Mas será que é verdade mesmo?",
			"Na contramão das ideias de todos, o sábio questiona e investiga se os dados são realmente verdadeiros. De onde saiu essa informação? Quais são as provas de que ela seja verdadeira? Isso faz com que o sábio descubra mentiras e reponha a verdade, como se vê em tantos filmes e telenovelas. A sua inteligência e as suas investigações são capazes de desmascarar os vilões.",
			"7. PLANEJAMENTO EXCESSIVO",
			"Por fim, há uma desvantagem considerável no arquétipo do sábio. O excesso de análise e de planejamento pode levá-lo à procrastinação na hora de agir. Em outras palavras, o sábio pode ser muito detalhista e perfeccionista na busca pela verdade e pelo conhecimento, o que o leva a apegar-se à teoria e deixar de colocar os seus saberes em prática.",
			"É o caso daquele empresário que faz inúmeras pesquisas de mercado e passa horas analisando os dados, mas nunca se sente seguro o suficiente para decidir como agir daqui por diante.",
			"Como você pode perceber, o arquétipo do sábio é aquele perfil de pessoas que buscam sempre o conhecimento e a informação fidedigna antes de tomar as suas decisões — o que é ótimo, em um mundo onde tantas pessoas agem de forma impulsiva. Contudo, não podemos permitir que essa aquisição de conhecimentos seja tão meticulosa a ponto de nos impedir de agir.",
		],
	},
	{
		name: "O Mago",
		image_path: "/assets/archetypes/mago.jpg",
		overview: [
			"O mago é um dos 12 arquétipos de Jung. Ele é caracterizado por um conhecimento que não é somente racional, mas também místico e espiritual. O seu objetivo é transformar sonhos em realidade, tanto os seus quanto os de outras pessoas. Assim, esse arquétipo procura desenvolver uma visão específica de vida e viver de acordo com ela.",
			"1. ENTENDER O UNIVERSO",
			"O objetivo do arquétipo do mago é o de compreender o universo em todas as suas possibilidades. O sábio tenta alcançar o mesmo objetivo, mas apenas com o uso da razão, enquanto o mago abre a sua mente para horizontes espirituais, compreendendo que entre o céu e a terra existem mais coisas do que os olhos alcançam.",
			"Dessa forma, o mago é um indivíduo que deseja, acima de tudo, adquirir conhecimentos de diferentes fontes, tentando compreender o sentido da vida. Mais do que isso, ele também deseja ser um ponto de luz para ajudar as outras pessoas.",
			"2. TRANSFORMAR SONHOS EM REALIDADE",
			"Se fôssemos escolher uma empresa ideal para representar o arquétipo do mago, ela com certeza seria a Disney. Trata-se de um universo paralelo, que realmente lembra a mágica e o encanto. É nela que as pessoas conseguem realizar os seus sonhos e ver coisas que vão muito além do que a ciência já é capaz de comprovar.",
			"Assim funciona também a mente dos que se identificam com esse arquétipo. O misticismo e a imaginação os levam a crer que tudo é possível, mesmo o mais complexo dos sonhos. Tudo pode se tornar real para quem realmente desejar.",
			"3. ENCONTRAR SOLUÇÕES EM QUE TODOS GANHAM",
			"Tomando como exemplo o já citado gênio da lâmpada, da história de Aladim, podemos compreender que o objetivo de quem carrega esse arquétipo é ajudar as pessoas a concretizar os seus objetivos, oferecendo-lhes possibilidades bastante sedutoras. Dessa forma, o mago consegue ajudar os indivíduos a alcançar as suas metas, mas também pensa em como ele mesmo pode tirar proveito da situação.",
			"Dessa forma, esses indivíduos, que se comunicam muito bem, procuram sempre encontrar soluções diplomáticas, ou seja, que ofereçam benefícios a todos, e não apenas a alguns. Por isso, eles têm certa tendência ao idealismo, o que pode levá-los a fugir momentaneamente da realidade.",
			"4. COMBINAR RAZÃO E INTUIÇÃO",
			"Conforme citamos, o mago e o sábio têm como ponto comum a busca pela sabedoria para a compreensão do universo. No entanto, enquanto o sábio o faz exclusivamente por meio da razão, o mago procura combiná-la a outras formas de conhecimento, como a espiritualidade e a própria intuição.",
			"Assim, esse arquétipo acredita em pensamentos e ideias que surgem aparentemente sem motivo, mas que têm o poder de ajudar as pessoas a encontrar aquilo que tanto procuram, o que pode ser chamado de intuição, auxílio espiritual, acaso, destino, e por aí vai. O caso é que nem todos os poderes e capacidades da vida, na visão desse arquétipo, podem ser explicados racionalmente.",
			"5. CONFIAR NO PODER DA MENTE",
			"Uma característica muito forte no mago é a confiança no poder da mente. Segundo as pessoas em que há identificação com esse arquétipo, os nossos pensamentos e sentimentos têm poderes e energias que podem tanto nos ajudar quanto nos atrapalhar na realização dos nossos sonhos.",
			"Por isso, ao mesmo tempo em que existem pensamentos positivos e construtivos, existem também as crenças limitantes que nos afastam das nossas metas. Dessa forma, o poder da mente precisa ser administrado e canalizado ao alcance de resultados extraordinários.",
			"6. CONFIAR EM SI MESMO",
			"O poder da mente conduz o mago à autoconfiança. Diante disso, esse arquétipo permite que o indivíduo conheça e acredite nas suas capacidades, talentos, conhecimentos e habilidades. É confiando em si mesma que uma pessoa consegue persistir até fazer dos seus sonhos uma realidade.",
			"No entanto, um cuidado que o mago deve tomar é o de não permitir que a sua introspecção e a sua autoconfiança se tornem arrogância ou individualismo. Mergulhar demais em si mesmo também pode fazer essas pessoas embarcarem na solidão, o que não é positivo.",
			"7. COMUNICAR SEM MANIPULAR",
			"O arquétipo do mago também representa o poder de comunicar, de encantar e de atrair as pessoas, com certo magnetismo para que façam aquilo que ele quer. Esse poder pode ser positivo, mas não pode ser confundido com a manipulação, ou seja, com o poder da comunicação utilizado apenas para benefício próprio.",
			"Dessa forma, cabe ao mago comunicar-se de forma clara e transparente, mas mantendo a ética e a empatia, sem sucumbir aos seus impulsos egoístas e manipuladores.",
			"O mago é um arquétipo de sabedoria, misticismo, compreensão do universo e vontade de ajudar. Ele deseja ampliar os seus horizontes de conhecimentos para compreender a vida, entendendo que nem tudo pode ser explicado pela razão. Assim, ele confia no poder da mente para concretizar os seus sonhos, mas também não pode tirar os pés da realidade e deixar de agir de forma mais concreta!",
		],
	},
	{
		name: "O Amante",
		image_path: "/assets/archetypes/amante.jpg",
		overview: [
			"O amante é um dos arquétipos junguianos que mais atraem o interesse das pessoas. Essencialmente emocional e intenso, esse arquétipo representa as pessoas que têm por objetivo relacionar-se de forma significativa com outras pessoas. Aqui, estamos falando não apenas do relacionamento amoroso, mas também da amizade, do apego à família, dos colegas de trabalho, e por aí vai.",
			"1. VAIDADE E SENSUALIDADE",
			"As pessoas que se identificam com o arquétipo junguiano do amante gostam de estar cercadas de pessoas. Para alcançarem esse objetivo, tornam-se vaidosas e sensuais. Por isso, estão sempre atentas à forma física, à beleza do rosto, às roupas, à maquiagem etc. Apreciam a arte e tudo aquilo que é essencialmente belo.",
			"Utilizam-se da sua sensualidade característica para seduzir a todos à sua volta e, com isso, alcançar os seus objetivos. No entanto, não fazem isso apenas como um meio para atingir um fim. De fato, são pessoas apaixonadas, que necessitam da aprovação e da companhia do outro — amigos, namorados, familiares, colegas de trabalho, chefes, vizinhos etc.",
			"2.VALORIZAÇÃO DOS DIFERENTES TIPOS DE AMOR",
			"Quando pensamos na palavra “amante”, imediatamente pensamos na sensualidade voltada ao romance. No entanto, o amante é um arquétipo que vivencia intensamente todas as formas de amor: o amor de irmãos, o amor de pais e filhos, o amor entre amigos, o amor entre colegas de profissão, o amor entre os membros de uma comunidade, e por aí vai.",
			"O amante tem uma necessidade de pertencimento, ou seja, de pertencer a diferentes grupos e de ser aceito pelo outro. Por isso, nesse caso, não falamos apenas do amor romântico, mas das relações humanas de maneira geral.",
			"3. DIFICULDADE DE FICAR SOZINHO",
			"A pior coisa que pode acontecer com o arquétipo do amante é ficar sozinho. Esse tipo de ser humano é particularmente extrovertido, o que significa que ele necessita da presença de outros indivíduos para renovar as suas energias.",
			"Além disso, esse tipo de pessoa é muito emotivo, sempre necessitando da companhia de alguém com quem possa expressar os seus sentimentos e compartilhar os seus momentos, sejam bons, sejam ruins. Assim, a solidão é o calcanhar de Aquiles desse arquétipo, que perde a motivação quando se sente excluído.",
			"4. EXPLORAÇÃO DOS 5 SENTIDOS",
			"Para atrair a atenção das pessoas e criar com elas um vínculo mais intenso, o amante faz uso dos 5 sentidos. É como se ele dominasse todas as linguagens do amor para mostrar-se como uma pessoa interessante.",
			"Assim, as pessoas com esse arquétipo forte dentro de si tendem a seduzir por meio do olhar, das expressões faciais, da linguagem corporal, da voz, das palavras, do contato, do perfume, das mensagens escritas, da música, da dança e das atitudes em geral. Todos os órgãos dos sentidos são estimulados para que essa pessoa se sinta querida, desejada e pertencente.",
			"5. SEDUÇÃO DE DIFERENTES FORMAS",
			"O amante é um sedutor nato. Conforme já citamos, ele atrai as pessoas ao seu redor por meio da vaidade e da beleza física, cuidando do rosto, do corpo, do vestuário, enfim da sua apresentação de maneira geral.",
			"Essa imagem pode parecer superficial à primeira vista, mas isso não se aplica ao amante. Esse arquétipo também seduz por outros meios, como a inteligência, a simpatia, a empatia, a solidariedade, a amizade, enfim, os meios de demonstrar o seu valor e conquistar a admiração do outro — mesmo nos menores gestos do dia a dia.",
			"6. CRIAÇÃO DE CONEXÕES PROFUNDAS",
			"Uma característica típica do amante é a vontade de se conectar com as pessoas. No entanto, essa conexão não se dá em um nível superficial. Em cada contato, esse arquétipo deseja se abrir, mostrar quem é e criar vínculos mais profundos, ou seja, conexões repletas de significado.",
			"Por isso, toda a sedução do amante não será útil para ele se só conseguir obter conversas superficiais e de pouca importância. O que ele realmente busca é uma conexão emocional, intelectual, espiritual e, em alguns casos, física. Trata-se de um arquétipo intenso, que se entrega a cada relação construída.",
			"7. VONTADE EXCESSIVA DE AGRADAR AO OUTRO",
			"Ser inteligente, bonito, comunicativo e simpático fatalmente torna o amante atraente. Contudo, a fraqueza desse arquétipo é justamente essa vontade excessiva de agradar ao outro. Quando em desequilíbrio, essa característica pode se tornar uma verdadeira submissão, em que o indivíduo faz tudo o que o outro quer — namorado, amigo, colega de trabalho, familiar etc.",
			"O medo de perder essas pessoas é tão grande que essa pessoa pode fazer até mesmo o que não quer apenas para satisfazer o outro. Dessa forma, esse arquétipo deve ficar atento para não anular a si mesmo e perder a própria identidade.",
			"Apaixonado, intenso, emotivo e sedutor: esse é o perfil do amante, um dos mais interessantes dos 12 arquétipos de Jung. Com todas essas características, ele procura estar sempre cercado de pessoas e construir com elas relações profundas. Contudo, o amante não pode anular a si mesmo nesse processo.",
		],
	},
	{
		name: "O Altruísta",
		image_path: "/assets/archetypes/altruista.jpg",
		overview: [
			"O altruísta, também conhecido como “o cuidador”, é um arquétipo junguiano que representa as pessoas compassivas e benevolentes. Ele tem um espírito paternal ou maternal, que se preocupa em cuidar do outro, protegendo-o e garantindo a sua segurança.",
			"1. EMPATIA",
			"O conceito de empatia refere-se à capacidade que alguns indivíduos têm de colocarem-se momentaneamente e mentalmente no lugar de outra pessoa. Assim, conseguem imaginar como eles mesmos se sentiriam, falariam a agiriam se estivessem naquela situação.",
			"Essa é uma característica muito forte nesse arquétipo. Sendo empáticos, os indivíduos com esse traço apresentam mais compaixão com o outro, procurando ouvi-lo para compreender a sua realidade, e não para julgá-lo em tom de superioridade, como se fosses juízes do que é certo e do que é errado.",
			"2. ALTRUÍSMO",
			"O altruísmo é o oposto do egoísmo, ou seja, é o ato de deixar de pensar apenas em si e de pensar também nas necessidades, nos desejos, nos medos e nos objetivos das outras pessoas. Quase sempre, a empatia e o altruísmo caminham juntos.",
			"O arquétipo do prestativo gosta e se esforça para conhecer a fundo a realidade do outro, especialmente no que diz respeito às suas fragilidades. É adquirindo esse conhecimento que esse tipo de pessoa entende como pode ajudar o próximo da melhor forma possível.",
			"3. CUIDADO E PROTEÇÃO",
			"Com empatia e altruísmo, esse arquétipo faz um exercício de momentaneamente desligar-se das preocupações que tem consigo mesmo, dedicando um pouco do seu tempo e dos seus esforços ao outro — que, na sua visão, precisa de mais atenção do que ele mesmo.",
			"Assim, é uma preocupação comum a todos os que se identificam com esse arquétipo a necessidade de cuidar, de proteger e de dar carinho. Nesse caso, estamos falando não apenas de pais e mães que cuidam dos seus filhos, mas de todos aqueles que agem dessa forma com os pais, com os irmãos, com os amigos, com os vizinhos e, muitas vezes, com completos desconhecidos.",
			"4. COMPAIXÃO E GENEROSIDADE",
			"Em consequência de todas as características já citadas, não fica difícil constatar que os trabalhos voluntários são muito frequentes em indivíduos com esse perfil. Essas pessoas gostam de ajudar o outro e sentem prazer ao fazê-lo — ao contrário de outros perfis, que podem ver a caridade e a solidariedade como fardos.",
			"Dessa forma, a compaixão e a generosidade tornam-se traços típicos do DNA do prestativo. Ele se sente feliz e realizado quando ajuda alguém. É quase como se essa fosse a sua missão de vida. Sentem-se úteis e valorosos quando conseguem levar algo de bom a um amigo, familiar, colega de trabalho, vizinho etc.",
			"5. DESEJO DE PROVER ESTABILIDADE E SEGURANÇA",
			"O arquétipo do prestativo fica bem fácil de identificar quando pensamos naqueles indivíduos que atuam como provedores. Estamos falando não apenas de pais e mães de família, mas também de empresários, de professores, de médicos, de enfermeiros, de bombeiros e de pessoas que atuam de modo voluntário para ajudar a sociedade em geral.",
			"O objetivo das ações desses indivíduos é levar mais estabilidade e segurança aos outros, sobretudo àqueles que se encontram em algum tipo de vulnerabilidade. Assim, procuram cuidar de quem estiver sofrendo, não importa qual seja o motivo. Se há um amigo desempregado, um primo doente ou um desconhecido passando fome, o prestativo certamente se interessará em ajudá-lo.",
			"6. PONTO DE ATENÇÃO 1: EXPLORAÇÃO",
			"Em meio a tantas virtudes, podemos acreditar que o prestativo praticamente não tem defeitos. Isso não é verdade, afinal de contas, todos os arquétipos têm as suas forças e os seus pontos de atenção.",
			"No caso do prestativo, ele precisa tomar muito cuidado para que a sua boa vontade não seja tomada como fraqueza ou ingenuidade. Nas mentes de quem é egoísta e perverso, a bondade desse arquétipo pode ser explorada excessivamente, em um abuso da solidariedade alheia.",
			"7. PONTO DE ATENÇÃO 2: ESQUECIMENTO DE SI MESMO",
			"Por fim, outro ponto que merece atenção por parte daqueles que se identificam com esse arquétipo é o esquecimento de si mesmo. Isso significa que boa parte dos indivíduos que dedicam muito esforço e muito tempo das suas vidas aos outros podem acabar deixando as próprias necessidades em segundo plano.",
			"Isso certamente não será positivo. Alguém que vive em função dos outros e negligencia o autocuidado e os próprios objetivos pode acabar adoecendo, física e/ou mentalmente. É bacana ser solidário, mas certamente poderemos ajudar mais pessoas quando nós mesmos estivermos bem também!",
			"Diante disso, podemos concluir que o prestativo é um indivíduo com espírito maternal e compassivo, sempre pronto para auxiliar os demais. O mundo realmente precisa de pessoas assim, sobretudo diante de tantos indivíduos sofrendo pelos mais diversos motivos. Essas pessoas têm um propósito nobre. Só não podem se esquecer de cuidar de si mesmas!",
		],
	},
	{
		name: "O Inocente",
		image_path: "/assets/archetypes/inocente.jpg",
		overview: [
			"Um indivíduo simples e otimista, mas que pode beirar a ingenuidade se não for cauteloso.",
			"1. OTIMISMO",
			"O otimismo é a marca registrada do inocente. Ele procura ter uma visão positiva sobre o mundo, sobre as coisas, sobre as pessoas e sobre a própria vida, de maneira geral. É aquela pessoa que consegue se maravilhar com a beleza de tudo o que estiver ao seu redor, como o sorriso de uma criança, a alegria de um animal ou o encanto de um pôr do sol.",
			"Mesmo nas horas mais difíceis, esses indivíduos conseguem enxergar algo positivo nos acontecimentos. Por isso, são pessoas que conseguem ser felizes no momento presente, e não apenas diante da conquista de grandes objetivos.",
			"2. SIMPLICIDADE",
			"Além de otimistas, os inocentes são também pessoas simples. O seu objetivo na vida é apenas ser feliz, o que não necessariamente envolve grandes posses e quantias absurdas de dinheiro. O que elas querem é ter o suficiente para viver com tranquilidade, de preferência transmitindo essa tranquilidade também para as pessoas que amam.",
			"Sabe aquele amigo que abriu mão de um emprego em uma notória empresa na cidade grande e foi viver no interior, em busca de paz, sossego e contato com a natureza? Então, muito provavelmente ele tem uma identificação com o arquétipo do inocente.",
			"3. PERFECCIONISMO",
			"A simplicidade de um inocente pode fazer com que eles sejam felizes com pouco. No entanto, essa busca pela felicidade pode não ser tão fácil quanto possa parecer. Por mais que o inocente esteja à procura de uma vida simples, ele pode ser bastante exigente com o presente e com o futuro.",
			"Por isso, esses indivíduos estão sempre à procura do lugar ideal para morar, do parceiro ideal com quem viver, do emprego ideal, dos filhos ideais, e por aí vai. São pessoas muito corretas na busca pelos seus objetivos e que, por isso, acabam cobrando que as pessoas ao seu redor também sejam assim “certinhas”, o que nem sempre ocorre.",
			"4. MOTIVAÇÃO",
			"O otimismo do inocente o leva a sempre crer que o alcance de um objetivo é possível. Dessa forma, alcançar motivação para essa pessoa não é algo difícil. Desde que ela visualize um futuro bom, correto e feliz, ela sente que todo esforço vale a pena.",
			"Dessa forma, quem tem esse arquétipo forte dentro de si não tem medo de estudar, de trabalhar, enfim, de dar o melhor de si para construir uma vida feliz. Mesmo que todos ao redor estejam dizendo que a meta definida é impossível de ser alcançada, o inocente acredita em si mesmo e ignora o pessimismo alheio, seguindo em frente no seu caminho.",
			"5. BUSCA PELO QUE É CORRETO",
			"O inocente, como o próprio nome do arquétipo sugere, é aquele indivíduo puro, que sempre tenta agir da melhor maneira e que dificilmente prejudicaria outra pessoa para alcançar os seus próprios objetivos.",
			"Por isso, esse arquétipo é muitas vezes visto como “certinho”, pois são pessoas que conhecem bem as regras e que evitam desobedecê-las, justamente porque acreditam que o caminho certo é o caminho da felicidade. São pessoas que não sabem conviver bem com a culpa de ter feito algum mal.",
			"6. LEALDADE E CONFIANÇA",
			"Outro traço muito comum entre aqueles que se identificam com o arquétipo do inocente é a lealdade. Essas pessoas querem ser felizes, mas desejam propagar essa felicidade aos seus amigos, vizinhos, colegas e familiares. São pessoas leais, as últimas de quem se poderia esperar uma traição.",
			"Esses indivíduos confiam nas pessoas, possivelmente porque acreditam que todos sejam bons como eles mesmos tentam ser. Por isso, fazem de tudo para defender aqueles a quem amam. Se tiverem que criticá-los por algum motivo, farão isso diretamente com a pessoa, e não a terceiros, o que seria visto como deslealdade.",
			"7. INGENUIDADE",
			"Otimistas, bondosos, corretos e leais: esses são os inocentes. São pessoas que, de fato, parecem estar no caminho da felicidade. Contudo, elas precisam ter muita cautela para que a sua inocência não se transforme em ingenuidade.",
			"Os inocentes tendem a ver os outros de acordo com a própria imagem. Por isso, podem cair na ilusão de que todo mundo será otimista, bondoso, correto e leal como eles — o que nem sempre é verdade. Assim, esses indivíduos tendem a sofrer quando percebem que os outros não fariam por eles aquilo que eles mesmos fariam pelos outros. Algo a ser trabalhado diariamente!",
			"Concluindo, o inocente é um arquétipo de Jung marcado pela pureza e pelo otimismo, mas que precisa ficar atento para que as outras pessoas, menos escrupulosas, tirem proveito do seu aspecto leal e correto. Procuram a felicidade nas coisas simples, mas, mesmo assim, essas pessoas podem ser perfeccionistas na busca por um mundo ideal.",
		],
	},
	{
		name: "O Rebelde",
		image_path: "/assets/archetypes/rebelde.jpg",
		overview: [
			"O arquétipo daqueles que se rebelam contra um sistema vigente, questionando as regras que, na sua visão, limitam a sua liberdade de agir e de ser quem são. “Fora da lei” ou “vivendo no limite” são títulos fáceis de atribuir a esses indivíduos.",
			"1. CONHECIMENTO DAS REGRAS",
			"Os rebeldes são indivíduos que não concordam com as regras. Por isso, desejam quebrá-las, sabotá-las, ignorá-las, modificá-las ou aboli-las. Contudo, antes de tomar qualquer decisão, precisam compreender bem as regras que tanto os incomodam.",
			"Ao contrário do que muitos pensam, um rebelde precisa ter um lado racional desenvolvido, pois ele precisa compreender com clareza o sistema contra o qual quer se rebelar — caso contrário, a sua atitude vira “rebeldia sem causa”, enfraquecendo a sua credibilidade. Por isso, todo rebelde precisa compreender a realidade em que está inserido, antes de questioná-la.",
			"2. DESOBEDIÊNCIA ÀS REGRAS",
			"Depois de adquirir um bom entendimento sobe o sistema, os rebeldes começam a desobedecer às regras que o compõem, por não concordar com elas. Eles questionam se todas essas leis e normas ainda fazem sentido, especialmente se estiverem beneficiando apenas um grupo de pessoas.",
			"Se pensarmos em grandes momentos da história, como a Revolução Francesa, perceberemos que eles foram conduzidos pelo arquétipo da rebeldia. Ideias como liberdade, igualdade e fraternidade a todos os cidadãos — o que hoje parece óbvio — estiveram, um dia, restritos à minoria.",
			"3. SEDE DE INDEPENDÊNCIA E LIBERDADE",
			"O arquétipo do rebelde é o que mais representa a vontade de ser um espírito livre, vivendo a vida de acordo com os seus próprios valores, e não de acordo com as regras que a sociedade determina.",
			"São indivíduos que questionam, por exemplo: quem disse que uma mulher precisa ser mãe para ser feliz? Quem disse que um homem não pode amar outro homem? Quem disse que jogar futebol é coisa de menino? Diversas crenças reproduzidas por muito tempo na sociedade começam a ser questionadas e contrariadas por aqueles que se sentem ofendidos ou excluídos por elas. É por isso que o objetivo do rebelde é a liberdade.",
			"4. LUTA POR MUDANÇAS E JUSTIÇA",
			"Quando um rebelde deseja modificar as regras, na maioria dos casos, ele o faz por realmente desejar mudanças positivas. Uma revolução em nome do povo é aquela que é contra privilégios da elite, sendo que todo ser humano tem direitos básicos que devem ser respeitados.",
			"Por isso, o que todo rebelde almeja com a sua desobediência às regras é a mudança. Ele contesta o jeito como as coisas funcionam hoje, de modo que possa encontrar um futuro mais favorável e justo a todos, e não apenas a um grupo social.",
			"5. CETICISMO E QUESTIONAMENTO",
			"O arquétipo rebelde é bastante cético. Isso significa que ele não acredita em tudo aquilo que lhe dizem ou que lhe é imposto. Ele não aceita que imponham a ele um determinado estilo de vida, especialmente se esse estilo vai contra a sua essência. É o caso de alguém que cresce em uma sociedade ditatorial, mas que acredita que a democracia é o melhor modelo de governo, por mais que não seja perfeito.",
			"Essa incompatibilidade entre os valores do indivíduo e os da sociedade que o cerca é o que o faz ser visto como rebelde. Assim, ele não acredita no que a sociedade impõe e começa a questionar as regras vigentes.",
			"6. MOMENTOS DE PREDOMÍNIO EMOCIONAL",
			"Identificar uma injustiça e querer mudar a realidade é um movimento que demanda muita força. Essa força, contudo, pode acabar vindo mais da emoção do que da razão — e é aí que o rebelde pode perder a sua eficácia.",
			"Por mais que os seus motivos sejam legítimos e que as causas defendidas façam sentido, os meios para lutar por elas não podem deixar a racionalidade de lado. Uma revolução que sai do controle e que começa a ser mais nociva do que benéfica tende a perder a razão e até mesmo o apoio popular.",
			"7. MOMENTOS DE CONFUSÃO ENTRE JUSTIÇA E VINGANÇA",
			"Por fim, outra fraqueza dos rebeldes pode ser a confusão existente entre os conceitos de justiça e vingança. A luta por justiça deve ter com base, de forma óbvia, o fim da injustiça, trazendo a sociedade a um sistema igualitário, sem que haja prejuízo de uns em benefício de outros. Já o desejo de vingança consiste em o oprimido tomar o lugar do opressor, cometendo basicamente os mesmos erros contra o seu antagonista.",
			"Essa confusão pode ocorrer e enfraquecer, por exemplo, movimentos de oposição política. Mudar as regras do jogo deve ser importante para tornar a sociedade mais justa, mas não para manter as injustiças, apenas mudando o lado dos times.",
			"O arquétipo rebelde está entre os mais conhecidos, mas também entre os mais polêmicos. As suas causas e os seus princípios podem ser nobres, mas os seus métodos de atuação também precisam ser, de modo que a sua conduta não seja enfraquecida e perca credibilidade.",
		],
	},
	{
		name: "O Bobo",
		image_path: "/assets/archetypes/bobo.jpg",
		overview: [
			"O comediante também conhecido como “bobo da corte”, é um dos arquétipos junguianos mais fáceis de reconhecer: trata-se do “palhaço” da família, do círculo de amigos, da sala de aula, entre outros ambientes. Esse indivíduo tem elevado senso de humor, é engraçado, gosta da diversão e de entreter quem estiver ao seu redor.",
			"1. DIVERSÃO E BUSCA PELO PRAZER",
			"O comediante é o arquétipo que mais busca pelo prazer. Para ele, a vida é, de fato, difícil e repleta de momentos menos felizes. Contudo, cabe a cada um de nós, na visão desse arquétipo, extrair o que houver de bom de cada momento. Por isso, essa é a representação daqueles indivíduos que vivem intensamente o momento presente.",
			"São pessoas que procuram a leveza no dia a dia, que pode ser bastante pesado e complexo. Dessa forma, gostam de rir, de viver momentos alegres, de cantar, de dançar, de contar piadas, enfim, de focar no que houver de bom em cada situação.",
			"2. DESEJO DE ENTRETER O OUTRO",
			"Para esse arquétipo, tão importante quanto divertir-se é fazer com que os outros se divirtam. Cada vez que um indivíduo com essas características percebe que está levando alegria às outras pessoas, ele também consegue se alegrar. Por isso, esse arquétipo representa todos os comediantes e palhaços — profissionais e amadores.",
			"Mr. Bean, Bob Esponja e Fábio Porchat são alguns exemplos de comediantes, da ficção e da vida real. Esse arquétipo é o mais forte naqueles indivíduos que conseguem passar por situações embaraçosas e dar risada de si mesmos, bem como permitir que os outros deem risada deles, sem que fiquem ofendidos ou envergonhados.",
			"3. SENSO DE HUMOR ELEVADO",
			"O comediante, como o nome automaticamente sugere, tem um elevado senso de humor. Isso significa que essas pessoas conseguem identificar graça e fazer piadas em diversos contextos, mesmo aqueles que aparentemente não tenham nada de divertido.",
			"É por isso que as pessoas com o talento para a comédia conseguem contar histórias engraças em situações comuns do cotidiano, como uma fila de padaria ou um trânsito carregado na cidade. Por isso, esses indivíduos dão risada e alegram quem estiver ao redor, mesmo nos momentos mais difíceis.",
			"4. ALEGRIA E OTIMISMO",
			"O comediante é, possivelmente, o mais alegre dos arquétipos junguianos. Isso não quer dizer que a vida dele seja fácil, mas sim que ele consegue tornar os seus dias mais felizes porque consegue se divertir, mesmo que esteja passando por adversidades.",
			"Trata-se daquela pessoa otimista, que enxerga o copo meio cheio, isto é, que identifica pequenos pontos positivos, mesmo que a situação geral seja negativa. Se for um bom comunicador, esse indivíduo consegue propagar a sua visão positiva às outras pessoas, tornando-se uma companhia muito agradável.",
			"5. NECESSIDADE DE PERTENCER",
			"Muitas vezes, o comportamento piadista, irreverente e debochado é um meio que o indivíduo encontra de pertencer a um grupo. Em geral, as pessoas gostam de conviver com quem é engraçado e apresenta bom humor. Por isso, o comediante, ao perceber que tem o poder de fazer as pessoas rirem, se utiliza dessa característica para ser aceito em diferentes grupos sociais.",
			"Trata-se de um mecanismo de conquista de amores, amizades, colegas de trabalho e até mesmo familiares. Ser engraçado é uma característica que abre portas a esses indivíduos, saciando a sua necessidade de pertencimento e aceitação.",
			"6. COMUNICAÇÃO AMOROSA, POR VEZES INGÊNUA",
			"Em geral, o comediante conta piadas para ser aceito. Por isso, a sua comunicação tende a ser cada vez mais alegre, simpática e amorosa. Contudo, há alguns indivíduos com o perfil do comediante que levam o seu lado engraçado para a provocação e para a ironia, o que pode ofender e afastar as pessoas.",
			"Outro problema que pode ocorrer com o comediante é ser ingênuo demais. Nesse caso, as pessoas ao redor podem rir DELE e não COM ELE. É bacana levar a alegria às pessoas, mas desde que o individuo não perca o respeito próprio.",
			"7. DIFICULDADE EM SER VISTO COM SERIEDADE",
			"Isso nos leva à maior fraqueza desse arquétipo: não ser visto com seriedade. Como o comediante é sempre associado ao bom humor e à alegria, existe um estranhamento quando, por algum motivo, ele se apresenta mais calmo, introspectivo, triste ou irritado.",
			"Ele pode não ser visto com seriedade em alguns contextos. Assim, um chefe, por exemplo, pode impedir um funcionário que apresenta esse perfil de conduzir uma reunião, pois teme que piadas inapropriadas sejam feitas. Dessa forma, por mais engraçado que o indivíduo seja, ele jamais deve permitir que essa característica seja confundida com imaturidade.",
			"O perfil geral do comediante é de alegria, otimismo e bom humor. As pessoas que se identificam com esse arquétipo conseguem enxergar o lado bom da vida e levar mais leveza a quem estiver ao seu redor. Contudo, precisam ter cautela para que não sejam vistos como imaturos, superficiais ou irresponsáveis.",
		],
	},
	{
		name: "O governante",
		image_path: "/assets/archetypes/governante.jpg",
		overview: [
			"Segundo Jung, esse arquétipo representa basicamente todos os indivíduos que apresentam o chamado “espírito de liderança”. Assim, são pessoas que lidam bem com o poder e com o controle em diferentes contextos, como a família, o grupo de amigos, a equipe de trabalho, a empresa, a comunidade etc.",
			"1. VONTADE DE PODER",
			"Em primeiro lugar, é importante ressaltar que o arquétipo do governante representa a vocação para o poder. Essa vocação contempla as habilidades de liderar, mas também a vontade de exercer o poder.",
			"Dessa forma, quem se identifica com esse arquétipo gosta de estar no comando das situações. É o tipo de pessoa que se sente preparado para comandar projetos e orientar equipes, delegando funções, acompanhando o desempenho de cada um, apontando ajustes, enfim, prestando auxílio de maneira geral. Sentem-se confortáveis estando nessa posição de comando.",
			"2. HABILIDADE DE CONTROLE",
			"São diversas as funções de um governante: definir metas e objetivos, traçar estratégias, delegar tarefas, definir indicadores de desempenho, acompanhar o andamento das atividades, dar feedbacks, motivar as equipes e controlar a maior parte do que as pessoas fazem.",
			"O governante precisa ter essa habilidade de controle, pois é ele quem responde pelos resultados da equipe. Ele pode e deve dividir os créditos e as críticas, mas deve compreender que a figura de referência será sempre ele. Por isso, as suas decisões precisam ter um mínimo de previsibilidade, acerca de resultados positivos.",
			"3. RESPONSABILIDADE",
			"O governante precisa ser o primeiro a dar o exemplo. Ele deve agir de acordo com a conduta que espera ver em todos os seus liderados. Por isso, esse arquétipo representa o trabalho, a dedicação, o estudo, a pontualidade, a disciplina, o empenho, a motivação, a comunicação clara e o bom relacionamento interpessoal.",
			"“Com grandes poderes vêm grandes responsabilidades”, como diz o famoso princípio de Peter Parker. Por isso, o governante deve agir sempre pensando nas consequências de cada um dos seus atos e decisões, tanto para si como para os demais membros da equipe.",
			"4. CAPACIDADE DE EXERCER A LIDERANÇA DE DIFERENTES FORMAS",
			"O arquétipo do governante representa todas as manifestações de liderança. Assim, ele pode ser identificado em diferentes contextos, como: liderar uma família, liderar um grupo de amigos, liderar uma empresa, liderar um departamento, liderar um projeto, liderar uma comunidade, liderar uma iniciativa, e por aí vai.",
			"Em todas essas situações, existe uma força centrada no indivíduo que é capaz de mobilizar os demais a agir de acordo com as suas orientações. Isso depende da sua credibilidade, da sua organização e da clareza da sua comunicação ao relacionar-se com todos.",
			"5. DESEJO DE ESTABILIDADE E SUPERIORIDADE",
			"Esse tipo de pessoa acredita que, estando no comando das situações, consegue obter mais segurança e estabilidade, tanto para si mesmo como para aqueles que dependem desse líder.",
			"Eles também podem expressar um desejo de superioridade e de se diferenciar dos demais. Assim, essas pessoas se sentem bem em lugares que representam o poder e a autoridade, como grandes salões, prédios altos, carros fortes, eventos grandiosos, e por aí vai. Além disso, cuidam da aparência e do vestuário como forma de expressar o seu poder.",
			"6. MÉTODOS DE ORGANIZAÇÃO E PLANEJAMENTO",
			"Em geral, aqueles que se identificam com o arquétipo do governante são pessoas metódicas. Isso significa que elas conseguem definir metas específicas, ou seja, um estado desejado. Em seguida, são capazes de traçar uma linha de ações que une o estado atual a esse estado desejado — essa linha é conhecida como planejamento estratégico.",
			"Diante disso, esses indivíduos apresentam o seu plano de ações a todos os seus liderados, conseguindo convencê-los de que as suas ideias são satisfatórias. Alguns líderes são mais democráticos, incluindo os liderados nessa fase de planejamento.",
			"7. POSSÍVEL TENDÊNCIA AO AUTORITARISMO",
			"Infelizmente, porém, nem todo governante é assim sensível e atento ao que os seus liderados dizem. Alguns deles não são democráticos e impõem as suas opiniões e decisões a todos, sem admitir qualquer questionamento ou visão contrária.",
			"Este é o ponto delicado do arquétipo do governante: ele precisa liderar sem que o poder suba à sua cabeça e o torne alguém arrogante e insensível às necessidades de quem estiver sob a sua responsabilidade. As ideias de superioridade e exclusividade não podem dominar esse ser e deixar de lado a prosperidade do seu grupo.",
			"O arquétipo do governante, portanto, reúne as características fundamentais de quem exerce ou deseja exercer a liderança e o poder. É uma posição de muita organização, comunicação, responsabilidade e planejamento. Um bom governante consegue ouvir o que os seus liderados têm a dizer, evitando propagar as suas ideias à força. Por isso, ele deve ser carismático e honesto, sem cair no autoritarismo.",
		],
	},
	{
		name: "O Explorador",
		image_path: "/assets/archetypes/explorador.jpg",
		overview: [
			"Um dos 12 arquétipos de Jung é o explorador, também conhecido como aventureiro. Trata-se de um indivíduo ousado e destemido, que está sempre em busca de novidades e explorando novas formas de agir, que vão além do que comumente é escolhido pelas pessoas.",
			"1. CORAGEM",
			"Um dos aspectos mais facilmente identificáveis no arquétipo aventureiro é a sua coragem. O conceito de coragem não deve ser entendido como a ausência de medo, mas sim como o reconhecimento dos medos e o ato de enfrentá-los. Ou você acha que Indiana Jones nunca se assustou com todos os perigos enfrentados em cada filme?",
			"Assim, o aventureiro é aquele indivíduo que identifica as suas fraquezas e os seus temores. Contudo, ele não adota uma postura de comodismo. Ao contrário, ele começa a refletir sobre tudo aquilo que ele pode fazer para enfrentar esses medos e agir, mesmo sentindo-os.",
			"2. RECÁLCULO DE ROTA",
			"Outro traço comum ao aventureiro é o seu espírito explorador. Esse tipo de pessoa não costuma se acomodar a um estilo de vida específico. Ele permanece naquele local, naquele relacionamento e naquele emprego, por exemplo, enquanto tudo isso estiver fazendo sentido para si. Entretanto, a partir do momento em que outra oportunidade pareça mais atrativa, ele não hesita em recalcular a sua rota da vida.",
			"Dessa forma, o aventureiro é um pouco desapegado, pois está sempre experimentando algo novo. Muda de residência, de emprego, de marcas, de hábitos e de interesses com certa frequência.",
			"3. ANSEIO PELA LIBERDADE",
			"Com base no que citamos no item anterior, podemos compreender que o que faz um aventureiro feliz é justamente ter opções de escolha. Ele não gosta de ter tudo planejado até o fim. Ao contrário, prefere deixar várias portas abertas, de modo que possa experimentá-las.",
			"O que ele realmente quer é viver a vida com liberdade para traçar os seus próprios caminhos e mudar a rota quando bem entender. Naturalmente, nem toda pessoa está disposta a conviver com alguém assim. Isso faz com que os aventureiros sejam mais individualistas, frequentemente vivendo sozinhos.",
			"4. DETERMINAÇÃO",
			"A determinação é a melhor amiga da coragem. Ser determinado significa definir metas e não desistir delas, mesmo que haja muitos obstáculos pelo caminho. Dessa forma, se um aventureiro encontrou o seu caminho e está altamente motivado com a rota escolhida, ele não vai parar enquanto não encontrar aquilo que procura.",
			"Essa determinação é resultado de motivação, autoconhecimento e ânimo, que são traços típicos dos aventureiros. Isso pode até ser confundido em alguns momentos com teimosia. Mesmo quando as ideias dos que se identificam com esse arquétipo pareçam muito absurdas aos olhares de quem vê de fora, os aventureiros seguem em frente.",
			"5. CURIOSIDADE",
			"O aventureiro é curioso por natureza. Ele se interessa por diferentes estilos de vida e deseja experimentá-los para saber o que acha deles. Por isso, ele gosta de investigar, de compreender, de conhecer diferentes realidades, de viajar para vários lugares, de conversar com pessoas variadas, e por aí vai.",
			"A sua curiosidade o leva a fugir do tédio, da rotina e das situações cotidianas — fatores que afastam o aventureiro da sua motivação e alegria de viver. A novidade é o combustível de cada dia desse arquétipo, e é por isso que ele gosta tanto de conhecer o que é novo.",
			"6. PIONEIRISMO",
			"Ser pioneiro é ser o primeiro, ou um dos primeiros, a fazer alguma coisa. Mesmo que ninguém tenha feito algo, o aventureiro se prontifica a ser o primeiro a fazê-lo. Isso é particularmente útil no empreendedorismo. Se ninguém criou um restaurante de sorvetes salgados, por exemplo, ele não hesita em ser o pioneiro, por mais que as ideias pareçam malucas, a princípio.",
			"Esse tipo de pessoa aproveita a curiosidade e a coragem para fazer aquilo que ninguém mais fez. Se o caminho desejado não existe, o aventureiro faz questão de criar esse caminho, deixando a sua marca para que outros possam segui-lo.",
			"7. ENTUSIASMO E EXPERIMENTAÇÃO",
			"Por fim, não podemos deixar de citar que o aventureiro tem um grande entusiasmo. Ele está sempre pensando em novos caminhos e em diferentes formas de fazer as coisas, fugindo de tudo aquilo que é comum e usual. Ele se empolga com a ideia de liberdade, sentindo-se extremamente feliz e motivado quando vê diferentes caminhos à sua escolha.",
			"Esse tipo de pessoa prefere a certeza do erro à incerteza de nunca ter tentado. Mesmo que um resultado tenha sido negativo, o aventureiro sente-se feliz por ter experimentado e tirado a dúvida. Em geral, ele lida bem com as consequências dos seus atos.",
			"O aventureiro, portanto, é o indivíduo que se entedia com facilidade e que gosta de experimentar tudo aquilo que é novo. Individualista, explorador e sedento por liberdade, ele não mede esforços para encontrar a sua felicidade, mesmo que ela esteja em lugares pouco procurados. No entanto, ele precisa ser capaz de lidar com os resultados das suas escolhas, que nem sempre serão os que ele esperava encontrar.",
		],
	},
];

const list = (req: NextApiRequest, res: NextApiResponse) => {
	res.setHeader("Access-Control-Allow-Origin", "*");
	res.setHeader(
		"Access-Control-Allow-Headers",
		"Origin, X-Requested-With, Content-Type, Accept"
	);
	res.status(200).json(data);
};

export default list;
